//! Example: what a `Serializer` gets for free, and what each freebie costs.
//!
//! Most of `Serializer` is required methods — no body, every format writes its
//! own. A handful have default bodies, and each default is a decision the trait
//! makes on a format's behalf when it stays silent. Three of them are visible
//! here:
//!
//! | method | default | what silence means |
//! |---|---|---|
//! | `serialize_i128` | returns an error | this format has no 128-bit integers |
//! | `is_human_readable` | returns `true` | render for people, not for size |
//! | `SerializeStruct::skip_field` | does nothing | a skipped field leaves no trace |
//!
//! `Verbose` overrides none of them. `Tuned` overrides all three. They share
//! every other line of their implementation, generated by one macro from one
//! set of tokens, so anything that differs in the output below is caused by a
//! default method and nothing else.
//!
//! The third row is the one worth staring at. `skip_field` doing nothing is
//! correct for a format that lists the fields it has, and wrong for a format
//! that positions fields by index — which is why the method exists at all
//! rather than the trait simply expecting `serialize_field` to be skipped.

use serde_core::ser::{self, Impossible, Serialize, SerializeStruct, Serializer};
use std::fmt::{self, Display};

#[derive(Debug)]
pub struct Error(String);

impl Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for Error {}

impl ser::Error for Error {
    fn custom<T: Display>(msg: T) -> Self {
        Error(msg.to_string())
    }
}

#[derive(Default)]
pub struct Session {
    out: String,
    events: Vec<String>,
}

/// Every default kept.
pub struct Verbose<'a>(&'a mut Session);
/// The same format with three defaults overridden.
pub struct Tuned<'a>(&'a mut Session);

pub struct VerboseStruct<'a> {
    session: &'a mut Session,
    written: usize,
}
pub struct TunedStruct<'a> {
    session: &'a mut Session,
    written: usize,
}

/// Generates one whole format. `$extra` is where a format's overrides go; for
/// `Verbose` it is empty, which is the entire experiment.
macro_rules! format_impl {
    ($ser:ident, $st:ident, { $($ser_extra:tt)* }, { $($st_extra:tt)* }) => {
        impl<'a> Serializer for $ser<'a> {
            type Ok = ();
            type Error = Error;

            type SerializeStruct = $st<'a>;
            type SerializeSeq = Impossible<(), Error>;
            type SerializeTuple = Impossible<(), Error>;
            type SerializeTupleStruct = Impossible<(), Error>;
            type SerializeTupleVariant = Impossible<(), Error>;
            type SerializeMap = Impossible<(), Error>;
            type SerializeStructVariant = Impossible<(), Error>;

            $($ser_extra)*

            fn serialize_struct(
                self,
                _name: &'static str,
                len: usize,
            ) -> Result<$st<'a>, Error> {
                self.0.events.push(format!("serialize_struct(len = {len})"));
                self.0.out.push('{');
                Ok($st {
                    session: self.0,
                    written: 0,
                })
            }

            fn serialize_str(self, v: &str) -> Result<(), Error> {
                self.0.out.push_str(&format!("{v:?}"));
                Ok(())
            }

            format_impl!(@scalars
                serialize_bool(bool) serialize_char(char)
                serialize_i8(i8) serialize_i16(i16) serialize_i32(i32) serialize_i64(i64)
                serialize_u8(u8) serialize_u16(u16) serialize_u32(u32) serialize_u64(u64)
                serialize_f32(f32) serialize_f64(f64));

            fn serialize_bytes(self, v: &[u8]) -> Result<(), Error> {
                self.serialize_str(&format!("<{} bytes>", v.len()))
            }
            fn serialize_none(self) -> Result<(), Error> {
                self.serialize_unit()
            }
            fn serialize_some<T>(self, value: &T) -> Result<(), Error>
            where
                T: ?Sized + Serialize,
            {
                value.serialize(self)
            }
            fn serialize_unit(self) -> Result<(), Error> {
                self.0.out.push_str("null");
                Ok(())
            }
            fn serialize_unit_struct(self, _name: &'static str) -> Result<(), Error> {
                self.serialize_unit()
            }
            fn serialize_unit_variant(
                self,
                _name: &'static str,
                _index: u32,
                variant: &'static str,
            ) -> Result<(), Error> {
                self.serialize_str(variant)
            }
            fn serialize_newtype_struct<T>(self, _name: &'static str, value: &T) -> Result<(), Error>
            where
                T: ?Sized + Serialize,
            {
                value.serialize(self)
            }
            fn serialize_newtype_variant<T>(
                self,
                _name: &'static str,
                _index: u32,
                _variant: &'static str,
                _value: &T,
            ) -> Result<(), Error>
            where
                T: ?Sized + Serialize,
            {
                Err(ser::Error::custom("this format handles scalars and structs"))
            }

            format_impl!(@compound
                serialize_seq(Option<usize>) -> SerializeSeq
                serialize_tuple(usize) -> SerializeTuple
                serialize_map(Option<usize>) -> SerializeMap);

            fn serialize_tuple_struct(
                self,
                _name: &'static str,
                _len: usize,
            ) -> Result<Impossible<(), Error>, Error> {
                Err(ser::Error::custom("this format handles scalars and structs"))
            }
            fn serialize_tuple_variant(
                self,
                _name: &'static str,
                _index: u32,
                _variant: &'static str,
                _len: usize,
            ) -> Result<Impossible<(), Error>, Error> {
                Err(ser::Error::custom("this format handles scalars and structs"))
            }
            fn serialize_struct_variant(
                self,
                _name: &'static str,
                _index: u32,
                _variant: &'static str,
                _len: usize,
            ) -> Result<Impossible<(), Error>, Error> {
                Err(ser::Error::custom("this format handles scalars and structs"))
            }
        }

        impl SerializeStruct for $st<'_> {
            type Ok = ();
            type Error = Error;

            fn serialize_field<T>(&mut self, key: &'static str, value: &T) -> Result<(), Error>
            where
                T: ?Sized + Serialize,
            {
                if self.written > 0 {
                    self.session.out.push_str(", ");
                }
                self.written += 1;
                self.session.out.push_str(key);
                self.session.out.push_str(": ");
                value.serialize($ser(&mut *self.session))
            }

            $($st_extra)*

            fn end(self) -> Result<(), Error> {
                self.session.out.push('}');
                Ok(())
            }
        }
    };

    (@scalars $($method:ident($ty:ty))*) => {
        $(
            fn $method(self, v: $ty) -> Result<(), Error> {
                self.0.out.push_str(&v.to_string());
                Ok(())
            }
        )*
    };

    (@compound $($method:ident($ty:ty) -> $assoc:ident)*) => {
        $(
            fn $method(self, len: $ty) -> Result<Self::$assoc, Error> {
                let _ = len;
                Err(ser::Error::custom("this format handles scalars and structs"))
            }
        )*
    };
}

format_impl!(Verbose, VerboseStruct, {}, {});

format_impl!(
    Tuned,
    TunedStruct,
    {
        /// The default returns an error. This format has room for the value, so
        /// it says so.
        fn serialize_i128(self, v: i128) -> Result<(), Error> {
            self.0.out.push_str(&v.to_string());
            Ok(())
        }

        /// The default returns `true`. Saying `false` changes what every
        /// `Serialize` impl in the program decides to send — see `Elapsed`.
        #[inline]
        fn is_human_readable(&self) -> bool {
            false
        }
    },
    {
        /// The default does nothing at all. A format that cares which fields
        /// were omitted has to say so here; there is no other hook.
        fn skip_field(&mut self, key: &'static str) -> Result<(), Error> {
            self.session.events.push(format!("skip_field({key:?})"));
            if self.written > 0 {
                self.session.out.push_str(", ");
            }
            self.written += 1;
            self.session.out.push_str(key);
            self.session.out.push_str(": -");
            Ok(())
        }
    }
);

/// A duration with two forms: one for people, one for machines.
///
/// This is the `Timestamp` pattern from serde_core's own `is_human_readable`
/// docs, and the only sanctioned way for a data structure to notice anything
/// about the format it is talking to.
pub struct Elapsed(pub u64);

impl Serialize for Elapsed {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        if serializer.is_human_readable() {
            let (h, m, s) = (self.0 / 3600, (self.0 % 3600) / 60, self.0 % 60);
            serializer.collect_str(&format_args!("{h}h {m:02}m {s:02}s"))
        } else {
            serializer.serialize_u64(self.0)
        }
    }
}

/// A struct with an optional field, serialized the way `serde_derive` writes it
/// when a field carries `skip_serializing_if`: the skipped field is announced
/// through `skip_field` and is not counted in the length.
pub struct Reading {
    pub elapsed: Elapsed,
    pub celsius: f64,
    pub note: Option<&'static str>,
}

impl Serialize for Reading {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let len = 2 + usize::from(self.note.is_some());
        let mut st = serializer.serialize_struct("Reading", len)?;
        st.serialize_field("elapsed", &self.elapsed)?;
        st.serialize_field("celsius", &self.celsius)?;
        match &self.note {
            Some(note) => st.serialize_field("note", note)?,
            None => st.skip_field("note")?,
        }
        st.end()
    }
}

fn line(name: &str, result: Result<String, Error>, events: &[String]) -> String {
    let shown = match result {
        Ok(text) => text,
        Err(e) => format!("error: {e}"),
    };
    let trailer = if events.is_empty() {
        String::new()
    } else {
        format!("   [{}]", events.join(", "))
    };
    format!("  {name:<9} {shown}{trailer}\n")
}

fn render<T: ?Sized + Serialize>(label: &str, value: &T) -> String {
    let mut out = format!("{label}\n");

    let mut session = Session::default();
    let result = value.serialize(Verbose(&mut session));
    out.push_str(&line(
        "Verbose",
        result.map(|()| session.out.clone()),
        &session.events,
    ));

    let mut session = Session::default();
    let result = value.serialize(Tuned(&mut session));
    out.push_str(&line(
        "Tuned",
        result.map(|()| session.out.clone()),
        &session.events,
    ));

    out
}

/// Every example exposes `run() -> String` rather than printing, so the same
/// code runs unchanged under `cargo test` and as WASM in the browser.
pub fn run() -> String {
    let mut out = String::new();

    out.push_str("Same format twice. Tuned overrides three default methods.\n\n");

    out.push_str(&render(
        "i128 value",
        &170_141_183_460_469_231_731_687_303_715_884_105_727i128,
    ));
    out.push_str("  the Verbose message is serde_core's own default body talking\n\n");

    out.push_str(&render("Elapsed(4_265)", &Elapsed(4_265)));
    out.push_str("  one Serialize impl, asking is_human_readable and believing the answer\n\n");

    out.push_str(&render(
        "Reading { note: Some(..) }",
        &Reading {
            elapsed: Elapsed(4_265),
            celsius: 21.5,
            note: Some("calibrated"),
        },
    ));
    out.push('\n');
    out.push_str(&render(
        "Reading { note: None }",
        &Reading {
            elapsed: Elapsed(4_265),
            celsius: 21.5,
            note: None,
        },
    ));
    out.push_str("  Verbose recorded no skip_field: its default body is just Ok(())\n");

    out.push_str(
        "\nNotice the length in the last case. Both formats were told len = 2,\n\
         because a skipped field is not counted; Verbose then wrote two fields\n\
         and Tuned wrote three. The length says what the data structure intends\n\
         to send, not what the format decides to emit.\n",
    );

    out
}
