//! Generates the example dispatch table from the `examples/` directory.
//!
//! Keeping this generated means adding an example cannot silently fail to
//! appear in the site. If the corresponding dependency is missing from
//! Cargo.toml, the generated code fails to compile and names the crate.

use std::path::PathBuf;

fn main() {
    let examples = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("playground has a parent")
        .join("examples");
    println!("cargo:rerun-if-changed={}", examples.display());

    let mut names: Vec<String> = std::fs::read_dir(&examples)
        .unwrap_or_else(|e| panic!("reading {}: {e}", examples.display()))
        .flatten()
        .filter(|e| e.path().join("Cargo.toml").is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    names.sort();

    for name in &names {
        assert!(
            name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
            "example directory {name:?} is not a valid crate identifier"
        );
    }

    let arms: String = names
        .iter()
        .map(|n| format!("        {n:?} => Some({n}::run()),\n"))
        .collect();
    let list: String = names.iter().map(|n| format!("{n:?}, ")).collect();

    let code = format!(
        "// @generated by build.rs from the examples/ directory — do not edit.\n\
         pub fn dispatch(name: &str) -> Option<String> {{\n    \
         match name {{\n{arms}        _ => None,\n    }}\n}}\n\n\
         pub const EXAMPLES: &[&str] = &[{list}];\n"
    );

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("dispatch.rs");
    std::fs::write(&out, code).unwrap_or_else(|e| panic!("writing {}: {e}", out.display()));
}
